sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shaluforwork/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shaluforwork/react-test npm test

after_success:
  - docker build -t shaluforwork/multi-client ./client
  - docker build -t shaluforwork/multi-nginx ./nginx
  - docker build -t shaluforwork/multi-server ./server
  - docker build -t shaluforwork/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shaluforwork/multi-client
  - docker push shaluforwork/multi-nginx
  - docker push shaluforwork/multi-server
  - docker push shaluforwork/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-550088095430"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
